### ISSUE TITLE
Render not working

### ISSUE THREAD

**Issue by lloricode** [fomvasss/laravel-meta-tags#4]
`fomvasss/laravel-meta-tags                           3.0.0 `

expected last version is not curretly working

```php
        MetaTag::setDefault([
            'viewport' => 'width=device-width, initial-scale=1, shrink-to-fit=no',
            'csrf-token' => csrf_token(),
            'title' => $title,
            'description' => $description,
            'author' => setting('site-author'),
            'keywords' => str_replace(' ', ',', strtolower($title)),
            //
            'og_type' => 'website',
            'og_url' => $fullUrl,
            'og_title' => $title,
            'og_description' => $description,
            'og_image' => $image,// app_logo('og_image'),
            //
            'twitter_title' => $title,
            'twitter_card' => 'summary_large_image',
            'twitter_site' => $fullUrl,
            'twitter_url' => $fullUrl,
            'twitter_description' => $description,
            'twitter_image' => $image,// app_logo('og_image'),
        ]);

        dd(__METHOD__, MetaTag::render());
```

![Screenshot from 2019-10-03 09-50-54](https://user-images.githubusercontent.com/8251344/66093550-50e3ca80-e5c3-11e9-9c6c-e7edbbe8faa2.png)

**Comment by lloricode** [comment]
wait i will check my part

**Comment by lloricode** [comment]
try to check this

```php
    /**
     * @return mixed
     */
    public function render()
    {
        return view($this->template, [
            'tags' => $this->get(),
            'path' => $this->getPath(),
        ])->render();
    }
```
ive notice the missing the `$config`

```php

    @foreach($config['available'] ?? [] as $key => $option)
        @if (isset($tags[$key]) && !in_array($key, ['h1']))

```

**Comment by lloricode** [comment]
solve just adding this on blade template

```php
@php
$config = config('meta-tags');
@endphp

```

**Comment by fomvasss** [comment]
Yes, there are a lot of changes in version 3!
This pack is not compatible with version 2
If you want to add your meta tags, you need to add them to the array in the configuration file (`config/meta-tags.php`) and write the output in the blade template
You can make pull-request blade `fomvasss/laravel-meta-tags/resources/views/tags.blade.php` with: twitter, csrf, viewport tags,.... for render

**Comment by fomvasss** [comment]
> solve just adding this on blade template
> 
> ```
> @php
> $config = config('meta-tags');
> @endphp
> ```

see `fomvasss/laravel-meta-tags/resources/views/tags.blade.php`. 
The `$config` variable was deleted and `config('meta-tags')` added
