### ISSUE TITLE
Breaking Change From v2 -> v3

### ISSUE THREAD

**Issue by juliomotol** [fomvasss/laravel-meta-tags#5]
We are planning to upgrade our application. Right now its currently using `fomvasss/laravel-meta-tags v2.0.1`. And while scrolling through the changes from `2.0.1...3.2.0`, there seem to been an undocumented breaking change. See the following diffs:
- [Model Diff from v3.2.0 -> v2.0.1](https://github.com/fomvasss/laravel-meta-tags/compare/2.0.1...3.2.0#diff-088d87a1766a0ee6d996b50dd1264023L14-R14)
- [Migration Diff from v3.2.0 -> v2.0.1](https://github.com/fomvasss/laravel-meta-tags/compare/2.0.1...3.2.0#diff-cb868e868c8789ee4a733048eb91fea3L23-R24)
- [Metatagable Trait Diff from v3.2.0 -> v2.0.1](https://github.com/fomvasss/laravel-meta-tags/compare/2.0.1...3.2.0#diff-b086be0bd31eb22fc56547a89f8a74f0L11-R11)

In our application, the `meta_tags` table already have `metatagable_id` and `metatagable_type`. This wouldn't be a problem if the project is is still in development, but we have other projects that uses this package and is **in production**. This could potentially break our application.

For the meantime we've found a work around by extending the `MetaTag` model and overriding the `$fillable` property and `metatagable()` method and using the that model in the `meta-tags.model` config.

**Comment by fomvasss** [comment]
OK. I am not going to make compatibility with previous old versions. You don't need to update them.

**Comment by juliomotol** [comment]
We kind of need to, we're bumping our Laravel dependencies. Laravel 6 and greater are not supported in `2.0.1`.

**Comment by fomvasss** [comment]
I added a new [tag 2.1.0](https://github.com/fomvasss/laravel-meta-tags/tree/2.1.0) that supports Laravel v6 and v7

**Comment by juliomotol** [comment]
Hi, we really appreciate the new release. After much thought, our team decided to just rename the table's columns with [Laravel's Documenation on Modifiyng Columns](https://laravel.com/docs/8.x/migrations#modifying-columns).

I have opened a [PR](https://github.com/fomvasss/laravel-meta-tags/pull/6) documenting an upgrade guide from v2 to v3.

Closing the issue in favor of the PR

**Comment by fomvasss** [comment]
Hi, Released v3.3.0
